/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ActivityLog {
  action: number;
  created_at: Generated<Timestamp>;
  gp_id: number;
  id: Generated<number>;
  user_id: number;
}

export interface Cities {
  country_id: number;
  id: Generated<number>;
  name: string;
  time_zone: Generated<string>;
}

export interface CitiesWithCountry {
  country_code: string | null;
  country_id: number | null;
  country_name: string | null;
  id: number | null;
  name: string | null;
  time_zone: string | null;
}

export interface Comments {
  comment: string;
  created_at: Generated<Timestamp>;
  gp_id: number | null;
  id: Generated<number>;
  reply_to_id: number | null;
  user_id: number;
}

export interface Countries {
  code: string;
  id: Generated<number>;
  name: string;
}

export interface GpRoundsPerYear {
  rounds: Int8 | null;
  year: Numeric | null;
}

export interface Gps {
  city_id: number;
  finished: Generated<boolean | null>;
  heats_finished: Generated<number | null>;
  id: Generated<number>;
  round: number;
  start_date: Timestamp;
  wild_card_id: number | null;
}

export interface PicksRecord {
  record: Int8 | null;
}

export interface Riders {
  active: number | null;
  country_id: number;
  id: Generated<number>;
  name: string;
  number: number;
  retired: boolean | null;
}

export interface RidersResults {
  gp_id: number;
  heats: Generated<number>;
  id: Generated<number>;
  medal: number | null;
  points: Generated<number>;
  pos: number | null;
  rider_id: number;
}

export interface RidersWithCountry {
  country_code: string | null;
  country_id: number | null;
  id: number | null;
  name: string | null;
  number: number | null;
}

export interface Users {
  auth0_id: string;
  created_at: Generated<Timestamp>;
  email: string;
  first_name: string;
  id: Generated<number>;
  last_name: string;
  reminder: Generated<boolean>;
}

export interface UsersPicks {
  created_at: Generated<Timestamp>;
  gp_id: number;
  id: Generated<number>;
  rider_1_id: number;
  rider_2_id: number;
  rider_3_id: number;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface UsersProgress {
  id: Generated<number>;
  positions: Generated<number[]>;
  user_id: number;
  year: number;
}

export interface UsersResults {
  gp_id: number;
  heats: Generated<number>;
  id: Generated<number>;
  medal_1: Generated<number>;
  medal_2: Generated<number>;
  medal_3: Generated<number>;
  points: Generated<number>;
  pos: number | null;
  user_id: number;
}

export interface UsersStandings {
  heats: Generated<number>;
  id: Generated<number>;
  medal_1: Generated<number>;
  medal_2: Generated<number>;
  medal_3: Generated<number>;
  points: Generated<number>;
  pos: number | null;
  prev_pos: number | null;
  user_id: number;
  year: number;
}

export interface UsersStars {
  id: Generated<number>;
  points: Generated<number>;
  type: number;
  user_id: number;
  year: number;
}

export interface UsersWithStars {
  first_name: string | null;
  id: number | null;
  last_name: string | null;
  stars: number[] | null;
}

export interface DB {
  activity_log: ActivityLog;
  cities: Cities;
  cities_with_country: CitiesWithCountry;
  comments: Comments;
  countries: Countries;
  gp_rounds_per_year: GpRoundsPerYear;
  gps: Gps;
  picks_record: PicksRecord;
  riders: Riders;
  riders_results: RidersResults;
  riders_with_country: RidersWithCountry;
  users: Users;
  users_picks: UsersPicks;
  users_progress: UsersProgress;
  users_results: UsersResults;
  users_standings: UsersStandings;
  users_stars: UsersStars;
  users_with_stars: UsersWithStars;
}
