/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Cities {
  id: Generated<number>;
  name: Generated<string>;
  nation_id: number;
}

export interface Comments {
  comment: string;
  date: Generated<Timestamp>;
  gp_id: number | null;
  id: Generated<number>;
  reply_to: number | null;
  user_id: number;
}

export interface Gps {
  city_id: number;
  finished: number | null;
  gp: number;
  id: Generated<number>;
  start: Timestamp | null;
  wild_card: number | null;
}

export interface Nations {
  id: Generated<number>;
  name: Generated<string>;
}

export interface Riders {
  active: number | null;
  id: Generated<number>;
  name: Generated<string>;
  nation_id: number;
  number: number;
  substitute: number | null;
}

export interface RidersResults {
  gp_id: number;
  heats: Generated<number>;
  id: Generated<number>;
  podium: number | null;
  points: Generated<number>;
  rider_id: number;
}

export interface Users {
  auth0_id: string;
  date_created: Generated<Timestamp>;
  email: Generated<string>;
  first_name: Generated<string>;
  id: Generated<number>;
  last_name: Generated<string>;
  reminder: Generated<number>;
}

export interface UsersPicksLog {
  date: Generated<Timestamp>;
  gp_id: number | null;
  id: Generated<number>;
  user_id: number | null;
}

export interface DB {
  cities: Cities;
  comments: Comments;
  gps: Gps;
  nations: Nations;
  riders: Riders;
  riders_results: RidersResults;
  users: Users;
  users_picks_log: UsersPicksLog;
}
